# Generated by Django 2.0 on 2018-07-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodemcu2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nodemcu1',
            new_name='nodemcu2',
        ),
    ]
