# Generated by Django 2.0 on 2018-07-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodemcu5', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nodemcu1',
            new_name='nodemcu5',
        ),
    ]
